package com.superdog.springboot.entity;

import com.lczyfz.edp.springboot.core.entity.DataEntity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotBlank;
import java.util.Date;

;

@ApiModel(value = "EsPaperStudent", description = "EsPaperStudent")
public class EsPaperStudent extends DataEntity<EsPaperStudent> {

    /**
     * 试卷编号
     * 表字段 : es_paper_student.paper
     *
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    @ApiModelProperty(value = "试卷编号")
    @NotBlank(message = "试卷编号不能为空")
    private String paper;

    /**
     * 考生编号
     * 表字段 : es_paper_student.student
     *
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    @ApiModelProperty(value = "考生编号")
    @NotBlank(message = "考生编号不能为空")
    private String student;

    /**
     * 开始作答时间点
     * 表字段 : es_paper_student.start_time
     *
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    @ApiModelProperty(value = "开始作答时间点")
    @NotBlank(message = "开始作答时间点不能为空")
    private Date startTime;

    /**
     * 结束作答时间点
     * 表字段 : es_paper_student.end_time
     *
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    @ApiModelProperty(value = "结束作答时间点")
    @NotBlank(message = "结束作答时间点不能为空")
    private Date endTime;

    /**
     * 提交标记
     * 表字段 : es_paper_student.submit_flag
     *
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    @ApiModelProperty(value = "提交标记")
    @NotBlank(message = "提交标记不能为空")
    private String submitFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_paper_student.paper
     *
     * @return the value of es_paper_student.paper
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    public String getPaper() {
        return paper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_paper_student.paper
     *
     * @param paper the value for es_paper_student.paper
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    public void setPaper(String paper) {
        this.paper = paper == null ? null : paper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_paper_student.student
     *
     * @return the value of es_paper_student.student
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    public String getStudent() {
        return student;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_paper_student.student
     *
     * @param student the value for es_paper_student.student
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    public void setStudent(String student) {
        this.student = student == null ? null : student.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_paper_student.start_time
     *
     * @return the value of es_paper_student.start_time
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_paper_student.start_time
     *
     * @param startTime the value for es_paper_student.start_time
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_paper_student.end_time
     *
     * @return the value of es_paper_student.end_time
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_paper_student.end_time
     *
     * @param endTime the value for es_paper_student.end_time
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_paper_student.submit_flag
     *
     * @return the value of es_paper_student.submit_flag
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    public String getSubmitFlag() {
        return submitFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_paper_student.submit_flag
     *
     * @param submitFlag the value for es_paper_student.submit_flag
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    public void setSubmitFlag(String submitFlag) {
        this.submitFlag = submitFlag == null ? null : submitFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_paper_student
     *
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createBy=").append(createBy);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", remarks=").append(remarks);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", paper=").append(paper);
        sb.append(", student=").append(student);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", submitFlag=").append(submitFlag);
        sb.append("]");
        return sb.toString();
    }
}