package com.superdog.springboot.entity;

import com.lczyfz.edp.springboot.core.entity.DataEntity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotBlank;

;

/**
 * @author superdog
 * @version 2023-3-27
 */
@ApiModel(value = "EsUser", description = "EsUser")
public class EsUser extends DataEntity<EsUser> {

    public static final String TEACHER = "teacher";

    public static final String STUDENT = "student";

    /**
     * 用户名
     * 表字段 : es_user.username
     *
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    @ApiModelProperty(value = "用户名")
    @NotBlank(message = "用户名不能为空")
    private String username;

    /**
     * 密码
     * 表字段 : es_user.password
     *
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    @ApiModelProperty(value = "密码")
    @NotBlank(message = "密码不能为空")
    private String password;

    /**
     * 角色
     * 表字段 : es_user.role
     *
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    @ApiModelProperty(value = "角色")
    @NotBlank(message = "角色不能为空")
    private String role;

    /**
     * 邮箱
     * 表字段 : es_user.email
     *
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    @ApiModelProperty(value = "邮箱")
    @NotBlank(message = "邮箱不能为空")
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_user.username
     *
     * @return the value of es_user.username
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_user.username
     *
     * @param username the value for es_user.username
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_user.password
     *
     * @return the value of es_user.password
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_user.password
     *
     * @param password the value for es_user.password
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_user.role
     *
     * @return the value of es_user.role
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_user.role
     *
     * @param role the value for es_user.role
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column es_user.email
     *
     * @return the value of es_user.email
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column es_user.email
     *
     * @param email the value for es_user.email
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_user
     *
     * @mbggenerated Sun Mar 26 22:52:59 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createBy=").append(createBy);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", remarks=").append(remarks);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", role=").append(role);
        sb.append(", email=").append(email);
        sb.append("]");
        return sb.toString();
    }
}