server:
  port: 20233
  tomcat:
    basedir: /usr/tomcat/tmpfile

resourceMapPath: /mnt/image/
cronQuartStart: false
apiPath: api
management:
  endpoint:
    mappings:
      enabled: false

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  servlet:
    multipart:
      # 上传一个文件最大值,默认1Mb
      max-file-size: 10MB
      # 上传多个文件最大值,50Mb,默认10Mb
      max-request-size: 100MB
  aop:
    proxy-target-class: true
  application:
    name: exam-system-main

  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/edp_base?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: mysql_ljh
      password: 123456

      #初始化时建立物理连接的个数
      initial-size: 3
      #最大连接池数量
      max-active: 100
      #最小连接池数量
      min-idle: 1
      #获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      #PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭
      pool-prepared-statements: false
      #指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      #statement池能够同时分配的打开的statements的最大数量。要启用PSCache，必须配置大于0
      max-open-prepared-statements: 0
      #用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 1 FROM t_user
      validation-query-timeout: 300000
      #申请连接时执行validationQuery检测连接是否有效
      test-on-borrow: true
      #归还连接时执行validationQuery检测连接是否有效
      test-on-return: true
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      ## 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      ## 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 10000000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'stat'监控统计用,'wall'用于防火墙,'log4j'日志用的
      filters: stat,wall
      #监控配置
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter.enabled: true
      web-stat-filter.url-pattern: /*
      web-stat-filter.exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet.enabled: true
      stat-view-servlet.url-pattern: /druid/*
      stat-view-servlet.reset-enable: false
      stat-view-servlet.login-username: qwe
      stat-view-servlet.login-password: asd
      stat-view-servlet.allow: 192.168.1.101,127.0.0.1
      stat-view-servlet.deny: 192.168.3.12


  redis:
    host: 192.168.101.33
    #    host: 192.168.1.220
    port: 6379
    database: 9
    password: 1234567
    jedis:
      pool:
        max-active: 16
        max-idle: 16
        min-idle: 2
        max-wait: -1
    timeout: 6000

  mail:
    host: smtp.qq.com
    port: 465

    username: test

    password: test

    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  #    host: smtp.qq.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  check-config-location: true

logging:
  level:
    com.lczyfz : debug
spring.activiti.check-process-definitions: false

edp:
  base:
    # jwt密钥
    jwt-secret: MjgxMGE2MWItMTM5My00ODAxLWFjY2YtZGE3OTRhZDk4ZjdjMDA1ZWY5ZGQtMzczMy00NGU3LTkyMWYtYWRmMGM5YjNlMzlh
    # jwt类型
    jwt-type: simple
    # token过期时间
    ttl-millis-access: 1209600000
    # refresh token过期时间
    ttl-millis-refresh: 86400000
    # 授权认证
    authorization: false
    # 授权项目名
    authorization-project-name: linked-big-data
    # 授权文件位置
    authorization-position: /usr/local/encoder.txt
    # 验证码开关
    validate-code: false
    # 密码有效期认证开关
    validity: false
    # 密码有效期时长
    validity-date: 30
    # 开启密码强度验证
    password-strength: true

file:
  # 禁止上传的文件类型扩展名
  forbidden-extension: exe, php, dll, jsp, js, bat, py, vbs, htm
  typeAliases:
    # 创建Bean时会根据此表额外生成others与all两个分类
    # 文件分类: 匹配文件contentType的正则表达式
    word: vnd.openxmlformats-officedocument.wordprocessingml.document|msword
    excel: vnd.openxmlformats-officedocument.spreadsheetml.sheet|vnd.ms-excel
    pdf: pdf
    image: image
    video: video
    ppt: vnd.openxmlformats-officedocument.presentationml.template|vnd.ms-powerpoint
    text: text
    compressed: zip|7z|tar|rar